### PR TITLE
fix: extra right padding when clearable=false

### LINKED ISSUE #1150: Clearable date range has extra padding on the right
**Describe the bug**
If the datepicker has a value longer than the input width AND is not clearable, in the place of `clear` icon, there is an extra margin which looks wrong.

**Expected behavior**
It is expected the text would not be cut before the input ends. Or in other words the right padding should be smaller.  

**Screenshots**
`:clearable="true"`
Image

`:clearable="false"`
Image

Of course I can override `padding-right` for this element locally, but would be good to have this solved upstream.

### PR DESCRIPTION
**Pull request by Amirkian2023**
## Describe your changes
Fixed extra right padding on the datepicker input when `clearable=false`. The padding now only applies when `clearable=true`, so the input text uses the full width correctly.

## Issue ticket number and link
Closes #1150

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have ensured that unit tests pass without errors
- [ ] If it is a new feature, I have added a new unit test

### CODE REVIEW

File: dev/serve.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <template>
     <div class="wrapper">
-        <Datepicker v-model="selectedDate" placeholder="Select Date" />
+        <Datepicker  v-model="selectedDate" placeholder="Select Date" />
```
Comment (Faq) [inline dev/serve.vue:3]: Why extra space? Seems unneeded.

Comment (Amirkian2023) [reply dev/serve.vue]: Good catch, thanks! 🙌  
I’ve remove space  from `dev/serve.vue`.
